# Generated by Django 4.2.16 on 2025-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationcode',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='activationcode',
            name='email',
            field=models.CharField(default='sd@mail.ru', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активна ли подписка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
