# Generated by Django 4.2.16 on 2024-12-12 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('text', 'Text Block'), ('image', 'Image Block'), ('video', 'Video Block'), ('profile', 'Profile Block'), ('product', 'Product Block'), ('link', 'Link Block'), ('quote', 'Quote Block'), ('contacts', 'Contacts Block'), ('delimiter', 'Delimiter Block')], max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('is_template', models.BooleanField(default=False, verbose_name='Шаблонный сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocks', models.ManyToManyField(blank=True, related_name='custom_sites', to='constructor.block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
