# Generated by Django 4.2.16 on 2024-12-11 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_of_block', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='Delimiter',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='GifBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
                ('image', models.ImageField(upload_to='gif_blocks/')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
                ('image', models.ImageField(upload_to='image_blocks/')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
                ('content', models.TextField()),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructor.block')),
                ('video_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            bases=('constructor.block',),
        ),
        migrations.CreateModel(
            name='CustomSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('is_template', models.BooleanField(default=False, verbose_name='Шаблонный сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocks', models.ManyToManyField(related_name='custom_sites', to='constructor.block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='constructor.blocktype'),
        ),
    ]
