# Generated by Django 4.2.16 on 2025-03-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsite',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_sites', to='constructor.customsite'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Text Block'), ('image', 'Image Block'), ('gif', 'Gif Block'), ('qanda', 'QandA Block'), ('social', 'Social Block'), ('video', 'Video Block'), ('profile', 'Profile Block'), ('product', 'Product Block'), ('link', 'Link Block'), ('quote', 'Quote Block'), ('contacts', 'Contacts Block'), ('delimiter', 'Delimiter Block'), ('gallery', 'Gallery Block'), ('mix', 'Mix block')], max_length=50, null=True),
        ),
    ]
