# Generated by Django 4.2.16 on 2025-04-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_customsite_template_alter_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsite',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
