# Generated by Django 4.2.16 on 2025-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_customsite_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsite',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR код'),
        ),
    ]
